#服务器端口：80
server:
  port: 80
  
spring:
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
  resources:
    staticLocations:
      classpath:/static/,
      classpath:/META-INF/resources/,
      classpath:/resources/,
      classpath:/public/,
      file:g:/coco
  #连接数据库配置  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cocoblog
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver

  mail:
      # 邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 1547171894@qq.com
      # 密码
      password: dfnvpefdhkaiggaf
      # 字符集编码
      default-encoding: UTF-8
      
# 以谁来发送邮件  自定义的参数
mail:
   sender:
      addr: 1547171894@qq.com
#bean实体类位置     
mybatis:
  type-aliases-package: com.yc.blog
  
#测试类配置  
logging:
  level:
    com:
      yc:
        blog:
          dao: debug
          #web:
            #hyq: warn